# coding: utf-8

"""
    Library Management API (v1)

    REST API cho hệ thống quản lý thư viện — phiên bản v1   Bao gồm quản lý người dùng, sách, mượn/trả sách, xác thực JWT, và khởi tạo database.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Loan(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'book_id': 'int',
        'borrow_date': 'datetime',
        'return_date': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'book_id': 'book_id',
        'borrow_date': 'borrow_date',
        'return_date': 'return_date'
    }

    def __init__(self, id=None, user_id=None, book_id=None, borrow_date=None, return_date=None):  # noqa: E501
        """Loan - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._book_id = None
        self._borrow_date = None
        self._return_date = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if user_id is not None:
            self.user_id = user_id
        if book_id is not None:
            self.book_id = book_id
        if borrow_date is not None:
            self.borrow_date = borrow_date
        if return_date is not None:
            self.return_date = return_date

    @property
    def id(self):
        """Gets the id of this Loan.  # noqa: E501


        :return: The id of this Loan.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Loan.


        :param id: The id of this Loan.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this Loan.  # noqa: E501


        :return: The user_id of this Loan.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Loan.


        :param user_id: The user_id of this Loan.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def book_id(self):
        """Gets the book_id of this Loan.  # noqa: E501


        :return: The book_id of this Loan.  # noqa: E501
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id):
        """Sets the book_id of this Loan.


        :param book_id: The book_id of this Loan.  # noqa: E501
        :type: int
        """

        self._book_id = book_id

    @property
    def borrow_date(self):
        """Gets the borrow_date of this Loan.  # noqa: E501


        :return: The borrow_date of this Loan.  # noqa: E501
        :rtype: datetime
        """
        return self._borrow_date

    @borrow_date.setter
    def borrow_date(self, borrow_date):
        """Sets the borrow_date of this Loan.


        :param borrow_date: The borrow_date of this Loan.  # noqa: E501
        :type: datetime
        """

        self._borrow_date = borrow_date

    @property
    def return_date(self):
        """Gets the return_date of this Loan.  # noqa: E501


        :return: The return_date of this Loan.  # noqa: E501
        :rtype: datetime
        """
        return self._return_date

    @return_date.setter
    def return_date(self, return_date):
        """Sets the return_date of this Loan.


        :param return_date: The return_date of this Loan.  # noqa: E501
        :type: datetime
        """

        self._return_date = return_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Loan, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Loan):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
