# coding: utf-8

"""
    Library Management API (v1)

    REST API cho hệ thống quản lý thư viện — phiên bản v1   Bao gồm quản lý người dùng, sách, mượn/trả sách, xác thực JWT, và khởi tạo database.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LoansBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'int',
        'book_id': 'int'
    }

    attribute_map = {
        'user_id': 'user_id',
        'book_id': 'book_id'
    }

    def __init__(self, user_id=None, book_id=None):  # noqa: E501
        """LoansBody - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._book_id = None
        self.discriminator = None
        if user_id is not None:
            self.user_id = user_id
        if book_id is not None:
            self.book_id = book_id

    @property
    def user_id(self):
        """Gets the user_id of this LoansBody.  # noqa: E501


        :return: The user_id of this LoansBody.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this LoansBody.


        :param user_id: The user_id of this LoansBody.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def book_id(self):
        """Gets the book_id of this LoansBody.  # noqa: E501


        :return: The book_id of this LoansBody.  # noqa: E501
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id):
        """Sets the book_id of this LoansBody.


        :param book_id: The book_id of this LoansBody.  # noqa: E501
        :type: int
        """

        self._book_id = book_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoansBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoansBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
