# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.loan import Loan  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total: int=None, page: int=None, limit: int=None, data: List[Loan]=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param total: The total of this InlineResponse2005.  # noqa: E501
        :type total: int
        :param page: The page of this InlineResponse2005.  # noqa: E501
        :type page: int
        :param limit: The limit of this InlineResponse2005.  # noqa: E501
        :type limit: int
        :param data: The data of this InlineResponse2005.  # noqa: E501
        :type data: List[Loan]
        """
        self.swagger_types = {
            'total': int,
            'page': int,
            'limit': int,
            'data': List[Loan]
        }

        self.attribute_map = {
            'total': 'total',
            'page': 'page',
            'limit': 'limit',
            'data': 'data'
        }
        self._total = total
        self._page = page
        self._limit = limit
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this InlineResponse2005.


        :return: The total of this InlineResponse2005.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this InlineResponse2005.


        :param total: The total of this InlineResponse2005.
        :type total: int
        """

        self._total = total

    @property
    def page(self) -> int:
        """Gets the page of this InlineResponse2005.


        :return: The page of this InlineResponse2005.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this InlineResponse2005.


        :param page: The page of this InlineResponse2005.
        :type page: int
        """

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this InlineResponse2005.


        :return: The limit of this InlineResponse2005.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this InlineResponse2005.


        :param limit: The limit of this InlineResponse2005.
        :type limit: int
        """

        self._limit = limit

    @property
    def data(self) -> List[Loan]:
        """Gets the data of this InlineResponse2005.


        :return: The data of this InlineResponse2005.
        :rtype: List[Loan]
        """
        return self._data

    @data.setter
    def data(self, data: List[Loan]):
        """Sets the data of this InlineResponse2005.


        :param data: The data of this InlineResponse2005.
        :type data: List[Loan]
        """

        self._data = data
