# coding: utf-8

"""
    Library Management API (v1)

    REST API cho hệ thống quản lý thư viện — phiên bản v1   Bao gồm quản lý người dùng, sách, mượn/trả sách, xác thực JWT, và khởi tạo database.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.auths_body import AuthsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthsBody(unittest.TestCase):
    """AuthsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthsBody(self):
        """Test AuthsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.auths_body.AuthsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
