# coding: utf-8

"""
    Library Management API (v1)

    REST API cho hệ thống quản lý thư viện — phiên bản v1   Bao gồm quản lý người dùng, sách, mượn/trả sách, xác thực JWT, và khởi tạo database.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.books_api import BooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self):
        self.api = BooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_books_get(self):
        """Test case for books_get

        Lấy danh sách tất cả sách (có tìm kiếm & phân trang)  # noqa: E501
        """
        pass

    def test_books_id_delete(self):
        """Test case for books_id_delete

        Xóa sách  # noqa: E501
        """
        pass

    def test_books_id_get(self):
        """Test case for books_id_get

        Lấy thông tin sách theo ID  # noqa: E501
        """
        pass

    def test_books_id_put(self):
        """Test case for books_id_put

        Cập nhật thông tin sách  # noqa: E501
        """
        pass

    def test_books_post(self):
        """Test case for books_post

        Thêm sách mới  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
