# coding: utf-8

"""
    Library Management API (v1)

    REST API cho hệ thống quản lý thư viện — phiên bản v1   Bao gồm quản lý người dùng, sách, mượn/trả sách, xác thực JWT, và khởi tạo database.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.loans_api import LoansApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoansApi(unittest.TestCase):
    """LoansApi unit test stubs"""

    def setUp(self):
        self.api = LoansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_loans_get(self):
        """Test case for loans_get

        Lấy danh sách lượt mượn (có tìm kiếm & phân trang)  # noqa: E501
        """
        pass

    def test_loans_id_return_patch(self):
        """Test case for loans_id_return_patch

        Trả sách  # noqa: E501
        """
        pass

    def test_loans_post(self):
        """Test case for loans_post

        Mượn sách mới  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
