# coding: utf-8

"""
    Library Management API (v1)

    REST API cho hệ thống quản lý thư viện — phiên bản v1   Bao gồm quản lý người dùng, sách, mượn/trả sách, xác thực JWT, và khởi tạo database.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auths_api import AuthsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthsApi(unittest.TestCase):
    """AuthsApi unit test stubs"""

    def setUp(self):
        self.api = AuthsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auths_post(self):
        """Test case for auths_post

        Đăng nhập  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
